### ISSUE TITLE
Online partial code not found

### ISSUE THREAD

**Issue by Sunskyoh** [pm-usp/concept_drift#1]
Hello, I have read your paper and admire your idea very much. The method you proposed includes the online clustering method (CluStream), but I did not see it in the code you provided. I sincerely hope that you can update the code to facilitate our subsequent study and further research.

**Comment by Sunskyoh** [comment]
> Hello, I have read your paper and admire your idea very much. The method you proposed includes the online clustering method (CluStream), but I did not see it in the code you provided. I sincerely hope that you can update the code to facilitate our subsequent study and further research.

To Rafael Gaspar de Sousa

**Comment by rafaelgasp** [comment]
Hello @Sunskyoh, 

I apologize for this issue, in fact I left the streaming clustering part of my implementation out of this repository. I just uploaded it now and merged it into the repo, here in this commit you can see the changes: https://github.com/pm-usp/concept_drift/commit/d00fe92557c7c1cd5aac520aad20b664099699c6

Thanks!

**Comment by Sunskyoh** [comment]
I have seen it. Thank you for your effort!
